<html>
    <body>
        <p>$Member.FirstName $Member.Surname just suggested that <strong>$Talk.PresentationTitle</strong> be moved to the category <strong>$SummitCategory.Name</strong>.</p>
        <p>If you agree that this ia good place for it, you can do the change by clicking here and logging in as an admin:</p>
        <p><a href="#">http://www.openstack.org/track-chairs/ChangeCategory/{$ID}/{$CategoryID}</a></p>
        
        <p>This email was automatically generated by the Track Chairs tool.</p>
    
    </body>
</html>