---
Name: election_module
After: 'framework/*','cms/*', 'openstack/*'
---
Member:
  extensions:
    - FoundationMember
EditProfilePage_Controller:
  extensions:
    - EditProfilePageElectionsExtension
MemberListPage_Controller:
  extensions:
    - MemberListPageElectionsExtension
