import 'babel/polyfill';
import 'array.prototype.move';
import 'array.prototype.find';
import 'array.prototype.findIndex';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import './css/theme.css';
import './less/style.less';
import './js/init';