module.exports = '<div class="single-voting-share">'+
					'<iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/tweet_button.26f01cfa05bff9af89657dcbd8f7b705.en.html#_=1425254465668&amp;count=none&amp;dnt=false&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http%3A%2F%2Fstatic.openstack.dev%2Fspeaker%2Fvoting%2Flogged-in%2F&amp;size=m&amp;text=Vote%20For%20Vancouver%20Summit%20Presentations%20%7C%20OpenStack%20Open%20Source%20Cloud%20Computing%20Software&amp;url=http%3A%2F%2Fstatic.openstack.dev%2Fspeaker%2Fvoting%2Flogged-in%2F" class="twitter-share-button twitter-tweet-button twitter-share-button twitter-count-none" title="Twitter Tweet Button" data-twttr-rendered="true" style="width: 57px; height: 20px;"></iframe>'+
					"<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>"+
				'</div>'+
				'<div class="single-voting-share">'+
					'<div id="___plus_0" style="text-indent: 0px; margin: 0px; padding: 0px; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; width: 58px; height: 20px; background: transparent;"><iframe frameborder="0" hspace="0" marginheight="0" marginwidth="0" scrolling="no" style="position: static; top: 0px; width: 58px; margin: 0px; border-style: none; left: 0px; visibility: visible; height: 20px;" tabindex="0" vspace="0" width="100%" id="I0_1425254465586" name="I0_1425254465586" src="https://apis.google.com/u/0/se/0/_/+1/sharebutton?plusShare=true&amp;usegapi=1&amp;action=share&amp;annotation=none&amp;origin=http%3A%2F%2Fstatic.openstack.dev&amp;url=http%3A%2F%2Fstatic.openstack.dev%2Fspeaker%2Fvoting%2Flogged-in%2F&amp;gsrc=3p&amp;ic=1&amp;jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en_GB.6Ex8sbqqgWI.O%2Fm%3D__features__%2Fam%3DAQ%2Frt%3Dj%2Fd%3D1%2Ft%3Dzcms%2Frs%3DAGLTcCNptsKqqHW7DF58vgC3jtM2Wf-Srw#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Conload&amp;id=I0_1425254465586&amp;parent=http%3A%2F%2Fstatic.openstack.dev&amp;pfname=&amp;rpctoken=93339510" data-gapiattached="true" title="+Share"></iframe></div>'+
				'</div>'+
				'<div class="single-voting-share fb-share">'+
					'<div class="fb-share-button fb_iframe_widget" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=600413776716536&amp;container_width=0&amp;href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;layout=button&amp;locale=en_US&amp;sdk=joey"><span style="vertical-align: bottom; width: 56px; height: 20px;"><iframe name="f112f561d8" width="1000px" height="1000px" frameborder="0" allowtransparency="true" scrolling="no" title="fb:share_button Facebook Social Plugin" src="http://www.facebook.com/v2.0/plugins/share_button.php?app_id=600413776716536&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FrFG58m7xAig.js%3Fversion%3D41%23cb%3Df7c476df4%26domain%3Dstatic.openstack.dev%26origin%3Dhttp%253A%252F%252Fstatic.openstack.dev%252Ff23884fc5%26relation%3Dparent.parent&amp;container_width=0&amp;href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;layout=button&amp;locale=en_US&amp;sdk=joey" style="border: none; visibility: visible; width: 56px; height: 20px;" class=""></iframe></span></div>'+
				'</div>';