import 'babel-polyfill';
import 'array.prototype.move';
import 'array.prototype.find';
import 'array.prototype.findindex';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import './less/theme.less';
import './less/style.less';
import './js/init';