<?php
/**
 * Copyright 2018 OpenStack Foundation
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/

/**
 * Class SummitTimeZoneMigration
 */
final class SummitTimeZoneMigration extends AbstractDBMigrationTask
{
    protected $title = "SummitTimeZoneMigration";

    protected $description = "SummitTimeZoneMigration";

    function doUp()
    {
        global $database;

        $HHVM_TIMEZONES = [
            0 => 'Africa/Abidjan' ,
            1 => 'Africa/Accra' ,
            2 => 'Africa/Addis_Ababa' ,
            3 => 'Africa/Algiers' ,
            4 => 'Africa/Asmara' ,
            5 => 'Africa/Bamako' ,
            6 => 'Africa/Bangui' ,
            7 => 'Africa/Banjul' ,
            8 => 'Africa/Bissau' ,
            9 => 'Africa/Blantyre' ,
            10 => 'Africa/Brazzaville' ,
            11 => 'Africa/Bujumbura' ,
            12 => 'Africa/Cairo' ,
            13 => 'Africa/Casablanca' ,
            14 => 'Africa/Ceuta' ,
            15 => 'Africa/Conakry' ,
            16 => 'Africa/Dakar' ,
            17 => 'Africa/Dar_es_Salaam' ,
            18 => 'Africa/Djibouti' ,
            19 => 'Africa/Douala' ,
            20 => 'Africa/El_Aaiun' ,
            21 => 'Africa/Freetown' ,
            22 => 'Africa/Gaborone' ,
            23 => 'Africa/Harare' ,
            24 => 'Africa/Johannesburg' ,
            25 => 'Africa/Juba' ,
            26 => 'Africa/Kampala' ,
            27 => 'Africa/Khartoum' ,
            28 => 'Africa/Kigali' ,
            29 => 'Africa/Kinshasa' ,
            30 => 'Africa/Lagos' ,
            31 => 'Africa/Libreville' ,
            32 => 'Africa/Lome' ,
            33 => 'Africa/Luanda' ,
            34 => 'Africa/Lubumbashi' ,
            35 => 'Africa/Lusaka' ,
            36 => 'Africa/Malabo' ,
            37 => 'Africa/Maputo' ,
            38 => 'Africa/Maseru' ,
            39 => 'Africa/Mbabane' ,
            40 => 'Africa/Mogadishu' ,
            41 => 'Africa/Monrovia' ,
            42 => 'Africa/Nairobi' ,
            43 => 'Africa/Ndjamena' ,
            44 => 'Africa/Niamey' ,
            45 => 'Africa/Nouakchott' ,
            46 => 'Africa/Ouagadougou' ,
            47 => 'Africa/Porto-Novo' ,
            48 => 'Africa/Sao_Tome' ,
            49 => 'Africa/Tripoli' ,
            50 => 'Africa/Tunis' ,
            51 => 'Africa/Windhoek' ,
            52 => 'America/Adak' ,
            53 => 'America/Anchorage' ,
            54 => 'America/Anguilla' ,
            55 => 'America/Antigua' ,
            56 => 'America/Araguaina' ,
            57 => 'America/Argentina/Buenos_Aires' ,
            58 => 'America/Argentina/Catamarca' ,
            59 => 'America/Argentina/Cordoba' ,
            60 => 'America/Argentina/Jujuy' ,
            61 => 'America/Argentina/La_Rioja' ,
            62 => 'America/Argentina/Mendoza' ,
            63 => 'America/Argentina/Rio_Gallegos' ,
            64 => 'America/Argentina/Salta' ,
            65 => 'America/Argentina/San_Juan' ,
            66 => 'America/Argentina/San_Luis' ,
            67 => 'America/Argentina/Tucuman' ,
            68 => 'America/Argentina/Ushuaia' ,
            69 => 'America/Aruba' ,
            70 => 'America/Asuncion' ,
            71 => 'America/Atikokan' ,
            72 => 'America/Bahia' ,
            73 => 'America/Bahia_Banderas' ,
            74 => 'America/Barbados' ,
            75 => 'America/Belem' ,
            76 => 'America/Belize' ,
            77 => 'America/Blanc-Sablon' ,
            78 => 'America/Boa_Vista' ,
            79 => 'America/Bogota' ,
            80 => 'America/Boise' ,
            81 => 'America/Cambridge_Bay' ,
            82 => 'America/Campo_Grande' ,
            83 => 'America/Cancun' ,
            84 => 'America/Caracas' ,
            85 => 'America/Cayenne' ,
            86 => 'America/Cayman' ,
            87 => 'America/Chicago' ,
            88 => 'America/Chihuahua' ,
            89 => 'America/Costa_Rica' ,
            90 => 'America/Creston' ,
            91 => 'America/Cuiaba' ,
            92 => 'America/Curacao' ,
            93 => 'America/Danmarkshavn' ,
            94 => 'America/Dawson' ,
            95 => 'America/Dawson_Creek' ,
            96 => 'America/Denver' ,
            97 => 'America/Detroit' ,
            98 => 'America/Dominica' ,
            99 => 'America/Edmonton' ,
            100 => 'America/Eirunepe' ,
            101 => 'America/El_Salvador' ,
            102 => 'America/Fort_Nelson' ,
            103 => 'America/Fortaleza' ,
            104 => 'America/Glace_Bay' ,
            105 => 'America/Godthab' ,
            106 => 'America/Goose_Bay' ,
            107 => 'America/Grand_Turk' ,
            108 => 'America/Grenada' ,
            109 => 'America/Guadeloupe' ,
            110 => 'America/Guatemala' ,
            111 => 'America/Guayaquil' ,
            112 => 'America/Guyana' ,
            113 => 'America/Halifax' ,
            114 => 'America/Havana' ,
            115 => 'America/Hermosillo' ,
            116 => 'America/Indiana/Indianapolis' ,
            117 => 'America/Indiana/Knox' ,
            118 => 'America/Indiana/Marengo' ,
            119 => 'America/Indiana/Petersburg' ,
            120 => 'America/Indiana/Tell_City' ,
            121 => 'America/Indiana/Vevay' ,
            122 => 'America/Indiana/Vincennes' ,
            123 => 'America/Indiana/Winamac' ,
            124 => 'America/Inuvik' ,
            125 => 'America/Iqaluit' ,
            126 => 'America/Jamaica' ,
            127 => 'America/Juneau' ,
            128 => 'America/Kentucky/Louisville' ,
            129 => 'America/Kentucky/Monticello' ,
            130 => 'America/Kralendijk' ,
            131 => 'America/La_Paz' ,
            132 => 'America/Lima' ,
            133 => 'America/Los_Angeles' ,
            134 => 'America/Lower_Princes' ,
            135 => 'America/Maceio' ,
            136 => 'America/Managua' ,
            137 => 'America/Manaus' ,
            138 => 'America/Marigot' ,
            139 => 'America/Martinique' ,
            140 => 'America/Matamoros' ,
            141 => 'America/Mazatlan' ,
            142 => 'America/Menominee' ,
            143 => 'America/Merida' ,
            144 => 'America/Metlakatla' ,
            145 => 'America/Mexico_City' ,
            146 => 'America/Miquelon' ,
            147 => 'America/Moncton' ,
            148 => 'America/Monterrey' ,
            149 => 'America/Montevideo' ,
            150 => 'America/Montserrat' ,
            151 => 'America/Nassau' ,
            152 => 'America/New_York' ,
            153 => 'America/Nipigon' ,
            154 => 'America/Nome' ,
            155 => 'America/Noronha' ,
            156 => 'America/North_Dakota/Beulah' ,
            157 => 'America/North_Dakota/Center' ,
            158 => 'America/North_Dakota/New_Salem' ,
            159 => 'America/Ojinaga' ,
            160 => 'America/Panama' ,
            161 => 'America/Pangnirtung' ,
            162 => 'America/Paramaribo' ,
            163 => 'America/Phoenix' ,
            164 => 'America/Port-au-Prince' ,
            165 => 'America/Port_of_Spain' ,
            166 => 'America/Porto_Velho' ,
            167 => 'America/Puerto_Rico' ,
            168 => 'America/Rainy_River' ,
            169 => 'America/Rankin_Inlet' ,
            170 => 'America/Recife' ,
            171 => 'America/Regina' ,
            172 => 'America/Resolute' ,
            173 => 'America/Rio_Branco' ,
            174 => 'America/Santarem' ,
            175 => 'America/Santiago' ,
            176 => 'America/Santo_Domingo' ,
            177 => 'America/Sao_Paulo' ,
            178 => 'America/Scoresbysund' ,
            179 => 'America/Sitka' ,
            180 => 'America/St_Barthelemy' ,
            181 => 'America/St_Johns' ,
            182 => 'America/St_Kitts' ,
            183 => 'America/St_Lucia' ,
            184 => 'America/St_Thomas' ,
            185 => 'America/St_Vincent' ,
            186 => 'America/Swift_Current' ,
            187 => 'America/Tegucigalpa' ,
            188 => 'America/Thule' ,
            189 => 'America/Thunder_Bay' ,
            190 => 'America/Tijuana' ,
            191 => 'America/Toronto' ,
            192 => 'America/Tortola' ,
            193 => 'America/Vancouver' ,
            194 => 'America/Whitehorse' ,
            195 => 'America/Winnipeg' ,
            196 => 'America/Yakutat' ,
            197 => 'America/Yellowknife' ,
            198 => 'Antarctica/Casey' ,
            199 => 'Antarctica/Davis' ,
            200 => 'Antarctica/DumontDUrville' ,
            201 => 'Antarctica/Macquarie' ,
            202 => 'Antarctica/Mawson' ,
            203 => 'Antarctica/McMurdo' ,
            204 => 'Antarctica/Palmer' ,
            205 => 'Antarctica/Rothera' ,
            206 => 'Antarctica/Syowa' ,
            207 => 'Antarctica/Troll' ,
            208 => 'Antarctica/Vostok' ,
            209 => 'Arctic/Longyearbyen' ,
            210 => 'Asia/Aden' ,
            211 => 'Asia/Almaty' ,
            212 => 'Asia/Amman' ,
            213 => 'Asia/Anadyr' ,
            214 => 'Asia/Aqtau' ,
            215 => 'Asia/Aqtobe' ,
            216 => 'Asia/Ashgabat' ,
            217 => 'Asia/Baghdad' ,
            218 => 'Asia/Bahrain' ,
            219 => 'Asia/Baku' ,
            220 => 'Asia/Bangkok' ,
            221 => 'Asia/Barnaul' ,
            222 => 'Asia/Beirut' ,
            223 => 'Asia/Bishkek' ,
            224 => 'Asia/Brunei' ,
            225 => 'Asia/Chita' ,
            226 => 'Asia/Choibalsan' ,
            227 => 'Asia/Colombo' ,
            228 => 'Asia/Damascus' ,
            229 => 'Asia/Dhaka' ,
            230 => 'Asia/Dili' ,
            231 => 'Asia/Dubai' ,
            232 => 'Asia/Dushanbe' ,
            233 => 'Asia/Gaza' ,
            234 => 'Asia/Hebron' ,
            235 => 'Asia/Ho_Chi_Minh' ,
            236 => 'Asia/Hong_Kong' ,
            237 => 'Asia/Hovd' ,
            238 => 'Asia/Irkutsk' ,
            239 => 'Asia/Jakarta' ,
            240 => 'Asia/Jayapura' ,
            241 => 'Asia/Jerusalem' ,
            242 => 'Asia/Kabul' ,
            243 => 'Asia/Kamchatka' ,
            244 => 'Asia/Karachi' ,
            245 => 'Asia/Kathmandu' ,
            246 => 'Asia/Khandyga' ,
            247 => 'Asia/Kolkata' ,
            248 => 'Asia/Krasnoyarsk' ,
            249 => 'Asia/Kuala_Lumpur' ,
            250 => 'Asia/Kuching' ,
            251 => 'Asia/Kuwait' ,
            252 => 'Asia/Macau' ,
            253 => 'Asia/Magadan' ,
            254 => 'Asia/Makassar' ,
            255 => 'Asia/Manila' ,
            256 => 'Asia/Muscat' ,
            257 => 'Asia/Nicosia' ,
            258 => 'Asia/Novokuznetsk' ,
            259 => 'Asia/Novosibirsk' ,
            260 => 'Asia/Omsk' ,
            261 => 'Asia/Oral' ,
            262 => 'Asia/Phnom_Penh' ,
            263 => 'Asia/Pontianak' ,
            264 => 'Asia/Pyongyang' ,
            265 => 'Asia/Qatar' ,
            266 => 'Asia/Qyzylorda' ,
            267 => 'Asia/Rangoon' ,
            268 => 'Asia/Riyadh' ,
            269 => 'Asia/Sakhalin' ,
            270 => 'Asia/Samarkand' ,
            271 => 'Asia/Seoul' ,
            272 => 'Asia/Shanghai' ,
            273 => 'Asia/Singapore' ,
            274 => 'Asia/Srednekolymsk' ,
            275 => 'Asia/Taipei' ,
            276 => 'Asia/Tashkent' ,
            277 => 'Asia/Tbilisi' ,
            278 => 'Asia/Tehran' ,
            279 => 'Asia/Thimphu' ,
            280 => 'Asia/Tokyo' ,
            281 => 'Asia/Tomsk' ,
            282 => 'Asia/Ulaanbaatar' ,
            283 => 'Asia/Urumqi' ,
            284 => 'Asia/Ust-Nera' ,
            285 => 'Asia/Vientiane' ,
            286 => 'Asia/Vladivostok' ,
            287 => 'Asia/Yakutsk' ,
            288 => 'Asia/Yekaterinburg' ,
            289 => 'Asia/Yerevan' ,
            290 => 'Atlantic/Azores' ,
            291 => 'Atlantic/Bermuda' ,
            292 => 'Atlantic/Canary' ,
            293 => 'Atlantic/Cape_Verde' ,
            294 => 'Atlantic/Faroe' ,
            295 => 'Atlantic/Madeira' ,
            296 => 'Atlantic/Reykjavik' ,
            297 => 'Atlantic/South_Georgia' ,
            298 => 'Atlantic/St_Helena' ,
            299 => 'Atlantic/Stanley' ,
            300 => 'Australia/Adelaide' ,
            301 => 'Australia/Brisbane' ,
            302 => 'Australia/Broken_Hill' ,
            303 => 'Australia/Currie' ,
            304 => 'Australia/Darwin' ,
            305 => 'Australia/Eucla' ,
            306 => 'Australia/Hobart' ,
            307 => 'Australia/Lindeman' ,
            308 => 'Australia/Lord_Howe' ,
            309 => 'Australia/Melbourne' ,
            310 => 'Australia/Perth' ,
            311 => 'Australia/Sydney' ,
            312 => 'Europe/Amsterdam' ,
            313 => 'Europe/Andorra' ,
            314 => 'Europe/Astrakhan' ,
            315 => 'Europe/Athens' ,
            316 => 'Europe/Belgrade' ,
            317 => 'Europe/Berlin' ,
            318 => 'Europe/Bratislava' ,
            319 => 'Europe/Brussels' ,
            320 => 'Europe/Bucharest' ,
            321 => 'Europe/Budapest' ,
            322 => 'Europe/Busingen' ,
            323 => 'Europe/Chisinau' ,
            324 => 'Europe/Copenhagen' ,
            325 => 'Europe/Dublin' ,
            326 => 'Europe/Gibraltar' ,
            327 => 'Europe/Guernsey' ,
            328 => 'Europe/Helsinki' ,
            329 => 'Europe/Isle_of_Man' ,
            330 => 'Europe/Istanbul' ,
            331 => 'Europe/Jersey' ,
            332 => 'Europe/Kaliningrad' ,
            333 => 'Europe/Kiev' ,
            334 => 'Europe/Kirov' ,
            335 => 'Europe/Lisbon' ,
            336 => 'Europe/Ljubljana' ,
            337 => 'Europe/London' ,
            338 => 'Europe/Luxembourg' ,
            339 => 'Europe/Madrid' ,
            340 => 'Europe/Malta' ,
            341 => 'Europe/Mariehamn' ,
            342 => 'Europe/Minsk' ,
            343 => 'Europe/Monaco' ,
            344 => 'Europe/Moscow' ,
            345 => 'Europe/Oslo' ,
            346 => 'Europe/Paris' ,
            347 => 'Europe/Podgorica' ,
            348 => 'Europe/Prague' ,
            349 => 'Europe/Riga' ,
            350 => 'Europe/Rome' ,
            351 => 'Europe/Samara' ,
            352 => 'Europe/San_Marino' ,
            353 => 'Europe/Sarajevo' ,
            354 => 'Europe/Simferopol' ,
            355 => 'Europe/Skopje' ,
            356 => 'Europe/Sofia' ,
            357 => 'Europe/Stockholm' ,
            358 => 'Europe/Tallinn' ,
            359 => 'Europe/Tirane' ,
            360 => 'Europe/Ulyanovsk' ,
            361 => 'Europe/Uzhgorod' ,
            362 => 'Europe/Vaduz' ,
            363 => 'Europe/Vatican' ,
            364 => 'Europe/Vienna' ,
            365 => 'Europe/Vilnius' ,
            366 => 'Europe/Volgograd' ,
            367 => 'Europe/Warsaw' ,
            368 => 'Europe/Zagreb' ,
            369 => 'Europe/Zaporozhye' ,
            370 => 'Europe/Zurich' ,
            371 => 'Indian/Antananarivo' ,
            372 => 'Indian/Chagos' ,
            373 => 'Indian/Christmas' ,
            374 => 'Indian/Cocos' ,
            375 => 'Indian/Comoro' ,
            376 => 'Indian/Kerguelen' ,
            377 => 'Indian/Mahe' ,
            378 => 'Indian/Maldives' ,
            379 => 'Indian/Mauritius' ,
            380 => 'Indian/Mayotte' ,
            381 => 'Indian/Reunion' ,
            382 => 'Pacific/Apia' ,
            383 => 'Pacific/Auckland' ,
            384 => 'Pacific/Bougainville' ,
            385 => 'Pacific/Chatham' ,
            386 => 'Pacific/Chuuk' ,
            387 => 'Pacific/Easter' ,
            388 => 'Pacific/Efate' ,
            389 => 'Pacific/Enderbury' ,
            390 => 'Pacific/Fakaofo' ,
            391 => 'Pacific/Fiji' ,
            392 => 'Pacific/Funafuti' ,
            393 => 'Pacific/Galapagos' ,
            394 => 'Pacific/Gambier' ,
            395 => 'Pacific/Guadalcanal' ,
            396 => 'Pacific/Guam' ,
            397 => 'Pacific/Honolulu' ,
            398 => 'Pacific/Johnston' ,
            399 => 'Pacific/Kiritimati' ,
            400 => 'Pacific/Kosrae' ,
            401 => 'Pacific/Kwajalein' ,
            402 => 'Pacific/Majuro' ,
            403 => 'Pacific/Marquesas' ,
            404 => 'Pacific/Midway' ,
            405 => 'Pacific/Nauru' ,
            406 => 'Pacific/Niue' ,
            407 => 'Pacific/Norfolk' ,
            408 => 'Pacific/Noumea' ,
            409 => 'Pacific/Pago_Pago' ,
            410 => 'Pacific/Palau' ,
            411 => 'Pacific/Pitcairn' ,
            412 => 'Pacific/Pohnpei' ,
            413 => 'Pacific/Port_Moresby' ,
            414 => 'Pacific/Rarotonga' ,
            415 => 'Pacific/Saipan' ,
            416 => 'Pacific/Tahiti' ,
            417 => 'Pacific/Tarawa' ,
            418 => 'Pacific/Tongatapu' ,
            419 => 'Pacific/Wake' ,
            420 => 'Pacific/Wallis' ,
            421 => 'UTC' ,
        ];

        Summit::$validation_enabled = false;
        foreach(Summit::get() as $summit){
            $time_zone = DB::query(sprintf("SELECT TimeZone FROM Summit WHERE ID = %s", $summit->ID))->value();
            if(is_null($time_zone)) continue;
            if(!isset($HHVM_TIMEZONES[intval($time_zone)])) continue;
            $summit->TimeZoneIdentifier = $HHVM_TIMEZONES[intval($time_zone)];
            $summit->write();
        }

        foreach(Election::get() as $election){
            $time_zone = DB::query(sprintf("SELECT TimeZone FROM Election WHERE ID = %s", $election->ID))->value();
            if(is_null($time_zone)) continue;
            if(!isset($HHVM_TIMEZONES[intval($time_zone)])) continue;
            $election->TimeZoneIdentifier = $HHVM_TIMEZONES[intval($time_zone)];
            $election->write();
        }

        if(DBSchema::existsColumn($database, "Election", "TimeZone")){
            DBSchema::dropColumn($database, "Election", "TimeZone");
        }

        if(DBSchema::existsColumn($database, "Summit", "TimeZone")){
            DBSchema::dropColumn($database, "Summit", "TimeZone");
        }
    }

    function doDown()
    {
        // TODO: Implement doDown() method.
    }
}