---
Name: fileextesions
---
File:
  allowed_extensions:
    - svg
    - ai
    - key
    - mp4
    - odp
    - jpg
    - jpeg
    - png
    - gif
    - pdf
    - doc
    - docx
    - txt
    - xls
    - xlsx
    - ppt
    - pptx
    - pps