---
Name: mainsiteroutes
After: 'framework/routes#coreroutes'
---
Director:
  rules:
    # needed for crontask ( CliController )
    '$Controller//$Action/$ID/$OtherID':  '*'
    'depsurvey': 'DeploymentSurveyController'
    'profile_images': 'ProfileImageApi'
    'api/v1/groups': 'GroupsApi'
    'api/v1/tags': 'TagsCrudApi'